name: Deploy Django App to Ubuntu Server

on:
  push:
    branches:
      - main

env:
  APP_NAME: issuetrackerdev
  APP_DIR: /home/ec2-user/apps/
  DEPLOY_DIR: /home/ec2-user/apps/issuetrackerdev
  WORKING_DIR: /home/ec2-user/apps/issuetrackerdev/issue_tracker_project
  MANAGE_PATH: /home/ec2-user/apps/issuetrackerdev/issue_tracker_project
  GUNICORN_SERVICE: issuetrackerdev_gunicorn.service
  GUNICORN_SOCKET: issuetrackerdev_gunicorn.socket
  NGINX_CONF_SRC: /home/ec2-user/service/issuetrackerdevbk
  NGINX_CONF_DEST: /etc/nginx/sites-available/issuetrackerdev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH to Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            APP_NAME=issuetrackerdev
            DEPLOY_DIR=/home/ec2-user/apps/$APP_NAME
            WORKING_DIR=$DEPLOY_DIR/issue_tracker_project
            MANAGE_PATH=$DEPLOY_DIR/issue_tracker_project
            GUNICORN_SERVICE=${APP_NAME}_gunicorn.service
            GUNICORN_SOCKET=${APP_NAME}_gunicorn.socket
            NGINX_CONF_SRC=/home/ec2-user/service/$APP_NAME
            NGINX_CONF_DEST=/etc/nginx/sites-available/$APP_NAME

            echo "Deploying app: $APP_NAME"

            # Create deploy directory if missing, fix ownership
            if [ ! -d "$DEPLOY_DIR" ]; then
              sudo mkdir -p "$DEPLOY_DIR"
              sudo chown -R $USER:$USER "$DEPLOY_DIR"
              sudo chmod -R 755 "$DEPLOY_DIR"
            fi

            # Clone or update repo and add safe.directory for git
            if [ -d "$DEPLOY_DIR/.git" ]; then
              cd $DEPLOY_DIR
              git config --global --add safe.directory $DEPLOY_DIR
              git reset --hard HEAD
              git clean -fd
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }} $DEPLOY_DIR
              git config --global --add safe.directory $DEPLOY_DIR
            fi

            # Setup and activate virtualenv, install requirements
            cd $WORKING_DIR
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Django management commands
            cd $MANAGE_PATH
            python manage.py makemigrations
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Copy Gunicorn service and socket files if they exist
            if [ -f "/home/ec2-user/service/$GUNICORN_SERVICE" ]; then
              sudo cp /home/ec2-user/service/$GUNICORN_SERVICE /etc/systemd/system/
            else
              echo "Warning: $GUNICORN_SERVICE not found"
            fi

            if [ -f "/home/ec2-user/service/$GUNICORN_SOCKET" ]; then
              sudo cp /home/ec2-user/service/$GUNICORN_SOCKET /etc/systemd/system/
            else
              echo "Warning: $GUNICORN_SOCKET not found"
            fi

            sudo systemctl daemon-reload

            # Start and enable Gunicorn socket
            sudo systemctl start $GUNICORN_SOCKET || true
            sudo systemctl enable $GUNICORN_SOCKET || true

            # Restart Gunicorn service if exists
            sudo systemctl restart $GUNICORN_SERVICE || echo "Gunicorn service restart failed"

            # Setup NGINX config and enable site
            if [ -f "$NGINX_CONF_SRC" ]; then
              sudo cp $NGINX_CONF_SRC $NGINX_CONF_DEST
              sudo mkdir -p /etc/nginx/sites-enabled
              if [ ! -L /etc/nginx/sites-enabled/$APP_NAME ]; then
                sudo ln -s $NGINX_CONF_DEST /etc/nginx/sites-enabled/$APP_NAME
              fi

              sudo nginx -t && sudo systemctl restart nginx
            else
              echo "Warning: NGINX config $NGINX_CONF_SRC not found, skipping NGINX reload"
            fi
